#!/usr/bin/env bash

CTX_SIZE=${CTX_SIZE:-32768}

set -e

# @cmd Starts a chat with the RemCLI
chat() {
	CTX_SIZE="$CTX_SIZE" ./chat.sh
}

# @cmd Starts the llama cpp server
server() {
	llama-server -hf unsloth/Qwen3.5-0.8B-GGUF -ngl 99 --flash-attn auto -t 6 -c $CTX_SIZE -b 512 --ubatch-size 128 --mlock
}

# @cmd Runs the test suite
test() {
	CTX_SIZE=$CTX_SIZE ./test/bats/bin/bats -p test/test.bats
}

# @cmd Parses the tools.ts file
tools() {
	bun run tools/tools.ts
}

# @cmd Runs the whole benchmark
benchmark() {
	CTX_SIZE=$CTX_SIZE ./test/bats/bin/bats -p test/benchmark.bats
}

# See more details at https://github.com/sigoden/argc
eval "$(start-tool extend)"
eval "$(argc --argc-eval "$0" "$@")"
