#!/usr/bin/env bash

set -e

# @cmd Starts a chat with the RemCLI
chat() {
	./chat.sh
}

# @cmd Starts the llama cpp server
server() {
	llama-server -hf unsloth/Qwen3.5-0.8B-GGUF -ngl 99 --flash-attn auto -t 6 -c 32768 -b 512 --ubatch-size 128 --mlock
}

# @cmd Runs the test suite
test() {
	./test/bats/bin/bats -p test/
}

# @cmd Parses the tools.ts file
tools() {
	bun run tools/tools.ts
}

# @cmd Runs the whole benchmark
benchmark() {
    echo TODO benchmark
}

# See more details at https://github.com/sigoden/argc
eval "$(start-tool extend)"
eval "$(argc --argc-eval "$0" "$@")"
